In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df = pd.read_csv("India_Unemployment_Synthetic_Dataset_100k.csv")
df

,Student_ID,Graduation_Year,State,Gender,Age,Degree_Level,Degree,Stream,College_Type,College_Tier,CGPA,Internship,Skills_Score,Employment_Status,Sector,Salary_LPA,Job_Search_Months,Urban_Rural
0,ST000001,2018,Kerala,Male,33,UG,B.Com,Computer Science,Government,Tier 1,5.13,No,28,Employed,Manufacturing,5.93,0,Urban
1,ST000002,2017,Karnataka,Female,30,UG,B.Sc,Marketing,Government,Tier 1,8.58,No,98,Employed,Banking,15.37,0,Urban
2,ST000003,2021,Delhi,Female,23,UG,B.Com,Chemistry,Government,Tier 3,6.90,No,38,Higher Studies,Retail,0.00,21,Rural
3,ST000004,2021,Maharashtra,Male,23,UG,B.Sc,Chemistry,Private,Tier 2,8.52,Yes,82,Unemployed,Retail,0.00,12,Urban
4,ST000005,2018,Telangana,Male,27,PG,MCA,Civil,Private,Tier 2,6.78,No,35,Unemployed,Government,0.00,23,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ST099996,2019,Maharashtra,Female,27,PG,MCA,Marketing,Government,Tier 1,9.84,Yes,85,Higher Studies,Manufacturing,0.00,20,Rural
99996,ST099997,2020,Rajasthan,Female,26,PG,MCA,Economics,Private,Tier 3,9.25,No,100,Higher Studies,Banking,0.00,17,Rural
99997,ST099998,2022,Tamil Nadu,Female,23,UG,B.Sc,Finance,Private,Tier 1,7.47,Yes,62,Employed,Banking,16.03,0,Urban
99998,ST099999,2024,Gujarat,Female,34,PG,MBA,Mechanical,Government,Tier 3,6.47,No,47,Employed,Manufacturing,16.29,0,Urban
99999,ST100000,2019,Karnataka,Female,21,UG,B.Tech,Finance,Private,Tier 3,6.46,No,8,Employed,Healthcare,18.91,0,Urban

In [36]:
df = df.drop(['Student_ID', 'Urban_Rural' , 'Job_Search_Months'], axis=1)
df

,Graduation_Year,State,Gender,Age,Degree_Level,Degree,Stream,College_Type,College_Tier,CGPA,Internship,Skills_Score,Employment_Status,Sector,Salary_LPA
0,2018,Kerala,Male,33,UG,B.Com,Computer Science,Government,Tier 1,5.13,No,28,Employed,Manufacturing,5.93
1,2017,Karnataka,Female,30,UG,B.Sc,Marketing,Government,Tier 1,8.58,No,98,Employed,Banking,15.37
2,2021,Delhi,Female,23,UG,B.Com,Chemistry,Government,Tier 3,6.90,No,38,Higher Studies,Retail,0.00
3,2021,Maharashtra,Male,23,UG,B.Sc,Chemistry,Private,Tier 2,8.52,Yes,82,Unemployed,Retail,0.00
4,2018,Telangana,Male,27,PG,MCA,Civil,Private,Tier 2,6.78,No,35,Unemployed,Government,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2019,Maharashtra,Female,27,PG,MCA,Marketing,Government,Tier 1,9.84,Yes,85,Higher Studies,Manufacturing,0.00
99996,2020,Rajasthan,Female,26,PG,MCA,Economics,Private,Tier 3,9.25,No,100,Higher Studies,Banking,0.00
99997,2022,Tamil Nadu,Female,23,UG,B.Sc,Finance,Private,Tier 1,7.47,Yes,62,Employed,Banking,16.03
99998,2024,Gujarat,Female,34,PG,MBA,Mechanical,Government,Tier 3,6.47,No,47,Employed,Manufacturing,16.29
99999,2019,Karnataka,Female,21,UG,B.Tech,Finance,Private,Tier 3,6.46,No,8,Employed,Healthcare,18.91

In [37]:
print('Shape:', df.shape)
print('\nDegrees:', df.Degree.unique())
print('\n:Salary_LPA', df.Salary_LPA.unique())
df.describe()

Shape: (100000, 15)

Degrees: ['B.Com' 'B.Sc' 'MCA' 'MBBS' 'B.Tech' 'MBA' 'BA' 'M.Tech']

:Salary_LPA [ 5.93 15.37  0.   ... 15.86  5.59 18.92]

,Graduation_Year,Age,CGPA,Skills_Score,Salary_LPA
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2020.996240,27.496850,7.494895,50.582380,7.441278
std,2.583225,4.608011,1.443271,28.904252,8.095047
min,2017.000000,20.000000,5.000000,1.000000,0.000000
25%,2019.000000,23.000000,6.230000,25.000000,0.000000
50%,2021.000000,28.000000,7.500000,51.000000,4.900000
75%,2023.000000,31.000000,8.740000,76.000000,14.490000
max,2025.000000,35.000000,10.000000,100.000000,24.000000